# Weather Data Visualizer - Lab Assignment 4 (FIXED)
# Ansh Verma - No Errors!

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from pathlib import Path

print("🌤️ Starting Weather Analysis...")

# Step 1: Create sample data (if no file exists)
if not os.path.exists('weather_data.csv'):
    print("📥 Creating sample data...")
    dates = pd.date_range('2024-01-01', periods=365, freq='D')
    data = {
        'date': dates,
        'temperature': 25 + 10 * np.sin(np.arange(365)/30) + np.random.normal(0, 2, 365),
        'rainfall': np.maximum(0, np.random.exponential(1, 365)),
        'humidity': 60 + 20 * np.sin(np.arange(365)/25) + np.random.normal(0, 5, 365)
    }
    df_raw = pd.DataFrame(data)
    df_raw.to_csv('weather_data.csv', index=False)
    print("✅ Sample data created!")

# Step 2: Load data
df = pd.read_csv('weather_data.csv')
df['date'] = pd.to_datetime(df['date'])
print(f"📊 Loaded {len(df)} days of weather data")

# Step 3: Clean data
df_clean = df.dropna()
print(f"✅ Clean data: {len(df_clean)} rows")

# Step 4: Statistics
print("\n📈 Key Stats:")
print(f"Temperature - Mean: {df_clean['temperature'].mean():.1f}°C, Max: {df_clean['temperature'].max():.1f}°C")
print(f"Rainfall - Total: {df_clean['rainfall'].sum():.0f}mm")

# Step 5: Monthly summary
df_clean['month'] = df_clean['date'].dt.month
monthly = df_clean.groupby('month').agg({
    'temperature': ['mean', 'max'],
    'rainfall': 'sum'
}).round(1)
print("\n📅 Monthly Summary:")
print(monthly)

# Step 6: Create ALL 4 plots
plt.style.use('default')
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Weather Data Dashboard - Lab Assignment 4', fontsize=16)

# Plot 1: Temperature trend
axes[0,0].plot(df_clean['date'], df_clean['temperature'], color='red', linewidth=1.5)
axes[0,0].set_title('Daily Temperature')
axes[0,0].set_ylabel('Temp (°C)')
axes[0,0].grid(True, alpha=0.3)

# Plot 2: Monthly rainfall
monthly_rain = df_clean.groupby('month')['rainfall'].sum()
axes[0,1].bar(monthly_rain.index, monthly_rain.values, color='blue')
axes[0,1].set_title('Monthly Rainfall')
axes[0,1].set_xlabel('Month')
axes[0,1].set_ylabel('Rain (mm)')

# Plot 3: Temp vs Humidity scatter
axes[1,0].scatter(df_clean['temperature'], df_clean['humidity'], alpha=0.6, s=20)
axes[1,0].set_title('Temp vs Humidity')
axes[1,0].set_xlabel('Temperature (°C)')
axes[1,0].set_ylabel('Humidity (%)')

# Plot 4: Monthly temp averages
monthly_temp = df_clean.groupby('month')['temperature'].mean()
axes[1,1].bar(monthly_temp.index, monthly_temp.values, color='orange')
axes[1,1].set_title('Avg Temp by Month')
axes[1,1].set_xlabel('Month')
axes[1,1].set_ylabel('Avg Temp (°C)')

plt.tight_layout()
plt.savefig('weather_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()
print("✅ Plot saved: weather_dashboard.png")

# Step 7: Export cleaned data
df_clean.to_csv('cleaned_weather.csv', index=False)
print("✅ Saved: cleaned_weather.csv")

# Step 8: Generate report
hottest_month = monthly_temp.idxmax()
rainiest_month = monthly_rain.idxmax()

report = f"""
WEATHER ANALYSIS REPORT
=======================

Dataset: 365 days (2024)
Records after cleaning: {len(df_clean)}

KEY FINDINGS:
- Hottest month: {hottest_month} ({monthly_temp.max():.1f}°C avg)
- Rainiest month: {rainiest_month} ({monthly_rain.max():.0f}mm)
- Temperature range: {df_clean['temperature'].min():.1f}°C to {df_clean['temperature'].max():.1f}°C

Generated by: Ansh Verma - Lab Assignment 4
"""

with open('weather_report.txt', 'w') as f:
    f.write(report)
print("✅ Report saved: weather_report.txt")
print(report)

print("\n🎉 ALL TASKS COMPLETE!")
print("Files created:")
print("- weather_dashboard.png")
print("- cleaned_weather.csv") 
print("- weather_report.txt")
